-- Add more reading texts for Spanish, German, and Chinese
-- Spanish Reading Texts
INSERT INTO public.reading_texts (language_code, title, content, difficulty, word_count, category) VALUES
-- Beginner Spanish
('es', 'The Market - El Mercado', 'Voy al mercado todos los sábados. En el mercado hay frutas frescas y verduras. Me gusta comprar manzanas, naranjas y plátanos. También compro tomates y lechuga para hacer ensalada. El vendedor es muy amable y siempre me da buenos precios. Después del mercado, tomo un café en la plaza.', 'beginner', 56, 'article'),
('es', 'My Dog - Mi Perro', 'Tengo un perro que se llama Max. Max es grande y tiene pelo marrón. Le gusta correr en el parque y jugar con la pelota. Cada mañana, Max y yo caminamos por una hora. Max es muy leal y siempre está feliz de verme cuando llego a casa. Es mi mejor amigo.', 'beginner', 58, 'story'),
('es', 'The School - La Escuela', 'Mi escuela está cerca de mi casa. Camino a la escuela con mis amigos cada día. Tenemos clases de matemáticas, ciencias, historia y español. Mi clase favorita es arte porque me gusta dibujar. Durante el almuerzo, comemos en la cafetería. Después de la escuela, jugamos fútbol en el campo deportivo.', 'beginner', 60, 'article'),

-- Intermediate Spanish
('es', 'The Trip to the Beach - El Viaje a la Playa', 'El verano pasado, mi familia y yo viajamos a la playa por una semana. Nos alojamos en un hotel con vista al mar. Durante el día, nadábamos en el océano y construíamos castillos de arena. Por las noches, caminábamos por el malecón y comíamos mariscos frescos en los restaurantes locales. Fue unas vacaciones inolvidables que siempre recordaré con cariño.', 'intermediate', 68, 'story'),
('es', 'Technology in Modern Life - La Tecnología en la Vida Moderna', 'La tecnología ha cambiado nuestra forma de vivir. Ahora podemos comunicarnos instantáneamente con personas en todo el mundo. Los teléfonos inteligentes nos permiten acceder a información ilimitada. Sin embargo, es importante encontrar un equilibrio entre el mundo digital y el real. Debemos recordar pasar tiempo de calidad con nuestros seres queridos sin distracciones tecnológicas.', 'intermediate', 65, 'article'),
('es', 'The First Day of Work - El Primer Día de Trabajo', 'Estaba nervioso en mi primer día de trabajo. Llegué temprano y conocí a mis nuevos colegas. Mi jefe me mostró la oficina y me explicó mis responsabilidades. Al principio, todo parecía complicado, pero mis compañeros fueron muy pacientes y me ayudaron a aprender. Al final del día, me sentía más confiado y emocionado por esta nueva etapa de mi vida profesional.', 'intermediate', 70, 'story'),

-- Advanced Spanish
('es', 'Climate Change and Our Future - El Cambio Climático y Nuestro Futuro', 'El cambio climático representa uno de los desafíos más apremiantes de nuestro tiempo. Los científicos advierten que las emisiones de gases de efecto invernadero están provocando un calentamiento global acelerado. Las consecuencias incluyen el derretimiento de los casquetes polares, el aumento del nivel del mar y eventos climáticos extremos más frecuentes. Es imperativo que los gobiernos, las empresas y los ciudadanos tomen medidas inmediatas para reducir nuestra huella de carbono y proteger el planeta para las generaciones futuras. La transición hacia energías renovables y prácticas sostenibles no es solo deseable, sino absolutamente necesaria.', 'advanced', 105, 'article'),
('es', 'Latin American Literature - La Literatura Latinoamericana', 'La literatura latinoamericana ha enriquecido el panorama literario mundial con voces únicas y perspectivas diversas. Desde el realismo mágico de Gabriel García Márquez hasta la poesía revolucionaria de Pablo Neruda, los escritores latinoamericanos han explorado temas universales a través de lentes culturales distintivas. Sus obras abordan la identidad, la política, el amor y la lucha social con una profundidad y belleza que trasciende fronteras. Este legado literario continúa inspirando a nuevas generaciones de escritores y lectores en todo el mundo.', 'advanced', 95, 'article'),

-- German Reading Texts
-- Beginner German
('de', 'My Daily Routine - Mein Tagesablauf', 'Ich stehe jeden Tag um sieben Uhr auf. Zuerst dusche ich und dann frühstücke ich. Ich esse meistens Brot mit Käse und trinke Kaffee. Um acht Uhr fahre ich zur Arbeit. Ich arbeite in einem Büro im Stadtzentrum. Nach der Arbeit gehe ich einkaufen oder treffe mich mit Freunden. Abends esse ich zu Hause und sehe fern.', 'beginner', 65, 'article'),
('de', 'The Weather - Das Wetter', 'Heute ist das Wetter sehr schön. Die Sonne scheint und der Himmel ist blau. Es ist warm, aber nicht zu heiß. Viele Menschen sind draußen im Park. Einige joggen, andere sitzen auf dem Gras und lesen Bücher. Kinder spielen auf dem Spielplatz. Im Café trinken die Leute Eis. Ich hoffe, das Wetter bleibt so schön.', 'beginner', 62, 'article'),
('de', 'My Hobby - Mein Hobby', 'Mein Lieblingshobby ist Fotografieren. Ich habe eine gute Kamera und gehe oft in die Natur. Ich fotografiere Landschaften, Tiere und Blumen. Am Wochenende besuche ich verschiedene Orte in der Stadt. Manchmal mache ich Porträts von meinen Freunden. Fotografie macht mir viel Spaß und ich lerne immer etwas Neues.', 'beginner', 55, 'article'),

-- Intermediate German
('de', 'German Cuisine - Die Deutsche Küche', 'Die deutsche Küche ist sehr vielfältig und regional unterschiedlich. Im Süden isst man gerne Schweinshaxe und Brezel, während im Norden Fischgerichte beliebter sind. Traditionelle deutsche Gerichte wie Sauerkraut, Bratwurst und Kartoffelsalat sind weltweit bekannt. In den letzten Jahren hat sich die deutsche Esskultur stark verändert. Heute findet man in deutschen Städten Restaurants mit internationaler Küche, und viele Menschen interessieren sich für vegetarische und vegane Ernährung.', 'intermediate', 75, 'article'),
('de', 'A Weekend in Berlin - Ein Wochenende in Berlin', 'Letzten Monat verbrachte ich ein Wochenende in Berlin. Die Stadt ist voller Geschichte und Kultur. Ich besuchte das Brandenburger Tor, die Berliner Mauer und verschiedene Museen. Besonders beeindruckend fand ich das Museum für Naturkunde. Abends genoss ich das lebhafte Nachtleben in Kreuzberg. Die Stadt hat eine einzigartige Atmosphäre, die traditionelle und moderne Elemente verbindet. Ich möchte unbedingt wiederkommen und mehr entdecken.', 'intermediate', 72, 'story'),
('de', 'The German Education System - Das deutsche Bildungssystem', 'Das Bildungssystem in Deutschland ist komplex und gut strukturiert. Nach der Grundschule besuchen Schüler verschiedene weiterführende Schulen: Gymnasium, Realschule oder Hauptschule. Das duale Ausbildungssystem kombiniert praktische Arbeit mit theoretischem Unterricht und ist international anerkannt. Deutsche Universitäten bieten qualitativ hochwertige Bildung, oft ohne hohe Studiengebühren. Dieses System hat Deutschland geholfen, eine starke Wirtschaft und qualifizierte Arbeitskräfte zu entwickeln.', 'intermediate', 70, 'article'),

-- Advanced German
('de', 'The Role of Renewable Energies - Die Rolle der erneuerbaren Energien', 'Deutschland hat sich als Vorreiter in der Energiewende etabliert. Die Bundesregierung hat ehrgeizige Ziele gesetzt, um den Anteil erneuerbarer Energien am Gesamtenergieverbrauch signifikant zu erhöhen. Windkraft und Solarenergie spielen dabei eine zentrale Rolle. Diese Transformation erfordert nicht nur technologische Innovationen, sondern auch eine umfassende Neugestaltung der Energieinfrastruktur. Herausforderungen wie die Energiespeicherung und die Netzstabilität müssen bewältigt werden. Dennoch zeigt Deutschland, dass eine nachhaltige Energiezukunft möglich ist, wenn politischer Wille und gesellschaftliches Engagement zusammenkommen.', 'advanced', 95, 'article'),
('de', 'The German Reunification - Die deutsche Wiedervereinigung', 'Der Fall der Berliner Mauer im November 1989 markierte einen historischen Wendepunkt. Die deutsche Wiedervereinigung am 3. Oktober 1990 beendete mehr als vier Jahrzehnte der Teilung. Dieser Prozess brachte enorme wirtschaftliche, soziale und kulturelle Herausforderungen mit sich. Ostdeutschland musste sich an die Marktwirtschaft anpassen, während Westdeutschland erhebliche finanzielle Ressourcen investierte. Trotz anfänglicher Schwierigkeiten hat Deutschland bemerkenswerte Fortschritte gemacht. Die Wiedervereinigung bleibt ein Symbol der Hoffnung und zeigt, dass scheinbar unüberwindbare Barrieren überwunden werden können.', 'advanced', 100, 'article'),

-- Chinese Reading Texts
-- Beginner Chinese
('zh', 'My Day - 我的一天', '我每天早上七点起床。我先刷牙洗脸，然后吃早饭。我喜欢吃包子和喝豆浆。八点我去上班。我在一家公司工作。中午我和同事一起吃午饭。下午五点下班后，我去超市买菜。晚上我做饭、看电视，然后十点睡觉。', 'beginner', 45, 'article'),
('zh', 'My Family - 我的家人', '我家有四口人：爸爸、妈妈、弟弟和我。爸爸是工程师，妈妈是老师。弟弟还在上中学。我们住在一个公寓里。周末的时候，我们全家人喜欢一起去公园散步。有时候我们也会去餐馆吃饭。我很爱我的家人。', 'beginner', 42, 'article'),
('zh', 'Going to the Supermarket - 去超市', '今天我去超市买东西。超市里有很多人。我买了苹果、香蕉、西红柿和黄瓜。我还买了牛奶、鸡蛋和面包。超市里的东西很新鲜。我用了一个小时买完所有的东西。然后我坐公交车回家。回家后，我把东西放进冰箱。', 'beginner', 48, 'story'),

-- Intermediate Chinese
('zh', 'Chinese Tea Culture - 中国的茶文化', '茶在中国有着几千年的历史。中国人喜欢喝茶，也把茶作为一种文化来欣赏。中国有很多种茶，比如绿茶、红茶、乌龙茶和普洱茶。不同的茶有不同的味道和功效。喝茶不仅是为了解渴，更是一种生活方式。在中国，人们常常用茶来招待客人，表示欢迎和尊重。茶艺表演也越来越受欢迎，展示了泡茶的艺术和美学。', 'intermediate', 70, 'article'),
('zh', 'Trip to Beijing - 北京之旅', '去年夏天，我和朋友们去北京旅游。我们参观了很多著名的景点，包括故宫、长城和天坛。故宫非常大，有很多古老的建筑。长城让我感到震撼，我无法想象古人是如何建造这样伟大的工程的。我们还品尝了北京烤鸭和其他传统美食。北京是一个充满历史和文化的城市。这次旅行让我对中国历史有了更深的了解。我希望将来能再次访问北京。', 'intermediate', 75, 'story'),
('zh', 'Experience Learning Chinese - 学习中文的经验', '学习中文是一个有趣但具有挑战性的过程。汉字很难记，因为它们与拼音文字完全不同。发音也很重要，因为声调会改变词语的意思。但是，我发现通过看中文电影、听中文音乐和与中国朋友交谈，我的中文水平提高了很多。现在我可以进行简单的对话，也能读懂一些文章。虽然还有很多要学习的，但我会继续努力，因为我热爱这门语言。', 'intermediate', 72, 'article'),

-- Advanced Chinese
('zh', 'China''s Economic Development - 中国的经济发展', '过去四十年来，中国经济经历了惊人的增长。改革开放政策开启了经济转型，使中国从计划经济转向市场经济。这一转变带来了巨大的变化：数亿人摆脱了贫困，城市化进程加快，科技创新蓬勃发展。然而，快速发展也带来了挑战，如环境污染、收入不平等和人口老龄化。中国政府正在努力解决这些问题，推动可持续发展。中国的经济模式为其他发展中国家提供了有价值的经验，同时也在全球经济中扮演着越来越重要的角色。', 'advanced', 95, 'article'),
('zh', 'The Impact of Modern Technology on Society - 现代科技对社会的影响', '科技进步深刻地改变了我们的生活方式。互联网和智能手机使信息传播变得即时和全球化。人工智能、大数据和云计算正在革新各个行业。电子商务改变了人们的购物习惯，远程工作变得越来越普遍。然而，技术发展也引发了一些担忧，包括隐私保护、网络安全和技术依赖。数字鸿沟可能加剧社会不平等。因此，我们需要在享受科技便利的同时，谨慎考虑其社会影响，确保技术发展能够造福全人类。', 'advanced', 100, 'article'),
('zh', 'The Integration of Tradition and Modernity - 传统与现代的融合', '在快速现代化的过程中，中国面临着如何平衡传统文化与现代生活的挑战。许多年轻人在全球化的影响下接受了西方文化，但同时也在重新发现传统文化的价值。中国传统节日如春节、中秋节仍然被广泛庆祝。传统艺术形式如书法、京剧和太极拳吸引了新一代的爱好者。同时，这些传统元素也在与现代设计和技术结合，创造出独特的当代中国文化。这种融合体现了文化的活力和适应性，也为世界文化多样性做出了贡献。', 'advanced', 105, 'article');

-- Add comment
COMMENT ON TABLE public.reading_texts IS 'Extended collection of reading texts for language learning in Spanish, German, and Chinese';
